default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username:
  password:
  socket: /tmp/mysql.sock

development: &development
  <<: *default
  host: db
  port: 3306
  database: deploy_development
  username: root
  password: password

test:
  <<: *default
  database: deploy_test
